---
title: twenty-six.design
timezone: UTC
collections:
  news:
    title: News
    output: true
    permalink: "/news/:title"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: default
name: twenty-six
description:
avatar:
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
google_analytics: UA-91441149-1
url: 
baseurl: ''
repository: jarrettfuller/twenty-six
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: :expanded
plugins:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
github: [metadata] 